### PR TITLE
Updated Legos.md with more Legos

### PR DESCRIPTION
**Pull request by satyvm**
Just added more legos with little info. Working on more things to add.

### CODE REVIEW

**Review by baokiddy — COMMENTED** [review]
Looks like these edits may require their own page since they are not quite Legos. @sarob @stefi-says can you weigh in on this?

**Comment by sarob** [comment]
Passport is a gitcoin lego as per https://github.com/Fraud-Detection-and-Defense/lego-docs and these are its bits.

**Review by sarob — COMMENTED** [review]
Passport is a gitcoin lego as per https://github.com/Fraud-Detection-and-Defense/lego-docs and these are its bits.

**Comment by epowell101** [comment]
please remove the reference to Passport - which is not what we are thinking of as a Lego.

Passport allows individuals to self identify as not being a Sybil.  This is related but NOT a Lego as we are defining Lego  cc @sarob @baokiddy

**Review by epowell101 — CHANGES_REQUESTED** [review]
people get confused about the comparison to Passport -
- could we remove 13-17

**Comment by sarob** [comment]
references to passport as a lego are removed, ready to merge @epowell101 @baokiddy @stefi-says ?

**Review by epowell101 — APPROVED** [review]
thanks for making the changes - and for all the additional submissions!

**Pull request merged**
