### PR TITLE
whats next for the hackathon submissions

### PR DESCRIPTION
**Pull request by sarob**
first steps outlined here from our ODC 31 jan 2023 meeting

### CODE REVIEW

**Comment by sarob** [comment]
Great reference of how to grow that can be applied here https://jordansegall.substack.com/p/so-how-many-stars-is-enough-a-data?sd=pf

**Comment by sarob** [comment]
reference issue #106 as similar to this PR

**Comment by poupou-web3** [comment]
On the sandbox on idea could be to discuss or provide guidance in collaboration with FDD 

> ODC will permanently publish the records of the Jan 2023 Hackathon and the resulting submissions and bounty winners via the [ODCDataforWeb3/Jan2023hackathon repository](https://github.com/OpenDataforWeb3/Jan2023hackathon)

I don't understand how you plan to do that.

> Update the OpenDataCommunity.org hackathon menu to point to the ODC Jan2023 Hackathon repository.

 I think a new page  is more appropriate and from that page we can redirect to past hackathons and future hackathons pages.

**Review by epowell101 — APPROVED** [review]
Nice - checklists FTW and more

**Pull request merged**
