### PR TITLE
Update faq.md #65

### PR DESCRIPTION
**Pull request by Nwakakukaks**
I have updated the FAQ to add more details to LEGOs explaining in great details what's a LEGO, existing LEGOs and ideas for new ones.  Please review and merge #65

### CODE REVIEW

**Comment by Nwakakukaks** [comment]
@epowell101 @sarob

**Review by epowell101 — CHANGES_REQUESTED** [review]
I am confused by this sentence:  In the case of Gitcoin Passport, Legos are used to identify Sybil attacks, which are attempts to manipulate a system by creating multiple fake identities.

Legos are related to but different than Passport.  I don't think we want to conflate them

I suggest you shorten it and remove direct reference to Passport - or rewrite it to be more clear.

**Review by curiousrabbit-eth — APPROVED** [review]
epowells comments were integrated

**Review by epowell101 — APPROVED** [review]
The language trips me up just a little bit - however I don't have anything better to suggest.  maybe I'm just tired while reading it :)

Thanks for doing the work and for taking our suggestions!

**Pull request merged**
