### PR TITLE
Added more FAQs for new contributors about ODC, LEGOS, Open Protocol …

### PR DESCRIPTION
**Pull request by krrsna37**
…and Landscape

Implements issue #65

### CODE REVIEW

**Review by epowell101 — CHANGES_REQUESTED** [review]
The sections about TrueBlocks and about Legos are confusing and note entirely accurate.

Thank you - however I would like these to not be included.  If you remove lines 224-242 and 171-181 then I'll support merging

**Review by krrsna37 — COMMENTED** [review]
More clarity was applied.

**Comment by sarob** [comment]
Needs a review and either approval or closure without merging.

**Comment by sarob** [comment]
Closing as will not do.

**Pull request closed without merging**
