### PR TITLE
updated to track with sandbox blogpost announcement

### PR DESCRIPTION
**Pull request by sarob**
and brainstorming in the miro board https://miro.com/app/board/uXjVPlv-XQA=/

### CODE REVIEW

**Review by poupou-web3 — COMMENTED** [review]
Where is the part on ## Regional and or local infrastructure to help with latency? Is it moved elsewhere?

**Review by epowell101 — COMMENTED** [review]
looks good - should we put a link to the Gitcoin Forum post - 
- https://gov.gitcoin.co/t/gitcoin-founded-opendata-community-kicks-off-databuilder-hackathon/12489/5?u=epowell101

**Comment by sarob** [comment]
> Where is the part on ## Regional and or local infrastructure to help with latency? Is it moved elsewhere?

Can be found in the miro board https://miro.com/app/board/uXjVPlv-XQA=/

**Comment by sarob** [comment]
> looks good - should we put a link to the Gitcoin Forum post -
> 
> * https://gov.gitcoin.co/t/gitcoin-founded-opendata-community-kicks-off-databuilder-hackathon/12489/5?u=epowell101

reference to the post added

**Review by poupou-web3 — APPROVED** [review]

**Pull request merged**
